language: php
php:
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install
  - mkdir build/logs -p

script:
  - phpunit

after_success:
  - vendor/bin/test-reporter

after_script:
  - rm -rf build/logs